version: '3.8'

services:
  bot-whatsapp:
    build: .
    container_name: bot-whatsapp
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CALENDAR_EMAIL=${GOOGLE_CALENDAR_EMAIL}
      - ADMIN_PHONE=${ADMIN_PHONE}
      - NODE_ENV=production
    volumes:
      # Persiste sessão do WhatsApp (CRÍTICO - não perder conexão)
      - whatsapp_session:/app/.wwebjs_auth
      # Persiste logs
      - bot_logs:/app/logs
      # Persiste exports de contatos
      - bot_exports:/app/exports
      # Config do Google Calendar (somente leitura)
      - bot_config:/app/config:ro
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    # Configurações específicas para WhatsApp Web
    shm_size: '2g'
    security_opt:
      - seccomp:unconfined

volumes:
  whatsapp_session:
    driver: local
  bot_logs:
    driver: local
  bot_exports:
    driver: local
  bot_config:
    driver: local

networks:
  bot-network:
    driver: bridge
  # Para conectar com N8N/Evolution API
  shared-network:
    external: true
    name: n8n_network  # Ajuste conforme sua rede existente
