version: '3.8'

services:
  bot-whatsapp:
    image: bot-whatsapp:latest
    
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      
      # 🔑 CONFIGURAÇÕES OPENAI
      - OPENAI_API_KEY=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
      
      # 📅 CONFIGURAÇÕES GOOGLE CALENDAR  
      - GOOGLE_CALENDAR_EMAIL=oswaldolrf@gmail.com
      - GOOGLE_CLIENT_EMAIL=cal-com@still-container-438022-e8.iam.gserviceaccount.com
      - GOOGLE_PROJECT_ID=still-container-438022-e8
      - GOOGLE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCJhVSAXo/iP/Kf\ncRZNUmAcPwu2taflOjKz8J9XdEEVl4JY8Gv7ZbOhYIGTc8LLHjag/v0bNOJCys6C\nD45JK9yOYsyYPzaeHvRFFK4P9UGmJ6JoOFAPVFRVqm7UMkVmayWXTOlWlDYpE2rO\nmQy1WiOXzmRddyoKvXrD/znBAlTMAYEzJzoTLHoUxuoubwsMz2+5lZQkxuEe50IJ\n8JdM7/SkgjGlp+yCddHoQeoGP6Qpwyw/N+xhFWPJbsJxVjkcNxOmHUhGB3LYeM5k\nwqam7KZocPPRTmfwImySbc+ihHIMP8300nRBiqJ0kDyO+gEwTC+hN992Wb4Zy8l4\nfGN9E6/pAgMBAAECggEAAvl0yfABqbGbZFJ0WojJFmNQtAt6zaz0EstGDwSvMbHc\numK82yuodnmZY+CRmoYVRWcuf0umBy7Ox6Zhe/isZRIC/doEKuhdfS8E0siJunfJ\n/foV1TcMOewdSI6rzJrNrdeWhm5fO4U1frF1wmhoM6zdo93jdWcCxEF9dMzBm8X2\ncJ+9LxRnR87UY1ZpS4+8npxZrsjiN8RM6w5UT1nd+ds1ElLzkusuxWl+68srecUJ\nbW+wUfCsRylhB8bVzrM/mhzFiqAiw11uVcK2r+3cY52Dhon9/8eiZVqqg7KR3cP9\nhCqIpToOHMPrrPXGbFW30oS6AVArgXT71F5h+pu/ZwKBgQC/intdpOeBTZ293Zjb\nHciNaF3K7L0h38V+lIgDZ9611uYwnU6UHpBYJ3qFh3SFGVfOdodUth7EBKTFIFWA\nCke06D35Nsq1K/Dj1t5hQfnh/fLH4SXHRpF+hu83dtx+GRVUZAK1om5HRA1HPoo1\nfCR2yKqnJDhke2p4yhe9k2tA2wKBgQC3zPCGC+rJmnFJiu+JmzkO3NOuSQCgVj7O\ngEpC3P+rCEVrZm/wTEgjlwMcYj4GPhvd7Juv2EuOjSLPU1/5W23TWAlzeAsYmxFo\nIHCEIH4K2qmrs+zuuPu5Cn1xujlqF34KpjQaDFZblUe7dB0xRWwM9m6apnBOCZFk\nqgU6jD87iwKBgCpdF6IDmgx4PT5EJ822zaexAKWkLMS0OHshoN+X9qMjT7BK6plK\nFUTaHngwGG5jx47rmkz7JtzV5hePajmyjF+Pyj03iCf/+vx5hp/eNsVsJGle+7sS\neZWRhJEw4d2l8JjEsfC4Z0mt3H34cBsaRPpcsZncIfjfbxIeKJgOZfdnAoGAY2Gg\nvBo9fXzQvJ8vHgycMXkdzCMU/50ioK2lebndVDFIt+XPqPLWHshMmlBUkTOMBdcl\n51Lgp9eQduHyBvZ0z83Obmz+MvPF2bOQoyCehmftTjYfaoUDNu6BHbk/yimhsUhk\n66C4IRT6kFUcY8PRxMCK1XwhRVDPGMsFwL6MgjkCgYEAnnuKQfmgZRpfVZM7UVgy\n2ISmmEv921f7C1Hzkszj8GWB+v4HVXpFL0yWWZbYDwcydmHWAtp4/U11crZzeQ/E\nhR3gPCOxVI5YxCL9MOoLhm2MBp9LWoUXmSx5f8Fq5SYFnle33t32XZ1CccDW3q/A\n/mnPAVFGyM8eu3QhAbShERg=\n-----END PRIVATE KEY-----
      
      # 📱 CONFIGURAÇÕES DO BOT
      - BOT_OWNER_NUMBER=5522981477000
      - DEFAULT_TIMEZONE=America/Sao_Paulo
      
    volumes:
      # Volumes nomeados para persistência
      - whatsapp_session:/app/.wwebjs_auth
      - bot_logs:/app/logs
      - bot_exports:/app/exports
      - bot_config:/app/config
      - bot_tmp:/app/tmp
      
    ports:
      - "3000:3000"
      
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot está rodando')"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
      
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  whatsapp_session:
    driver: local
  bot_logs:
    driver: local
  bot_exports:
    driver: local
  bot_config:
    driver: local
  bot_tmp:
    driver: local
